package:
  name: hydroid
  version: "0.1.0"

source:
  fn: v0.1.0.tar.gz
  url: https://github.com/ncbi/HYDROID/archive/v0.1.0.tar.gz
#  md5: d7936180ad4037962401c2302c1edd19
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hydroid = hydroid:main
    #
    # Would create an entry point called hydroid that calls hydroid.main()

    - HYDROID_test_exp=hydroid.command_line:test_exp
    - HYDROID_test_pred=hydroid.command_line:test_pred
    - HYDROID_get_ex1=hydroid.command_line:HYDROID_get_ex1
    - HYDROID_get_ex2=hydroid.command_line:HYDROID_get_ex2

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - biopython ==1.68
    - matplotlib ==2.0.0
    - numpy ==1.11.0
    - pandas >=0.19.2
    - peakutils >=1.0.3
    - pillow ==4.0.0
    - scipy ==0.18.1
    - statsmodels ==0.8.0
    - freesasa # [not win32]

  run:
    - python
    - biopython ==1.68
    - matplotlib ==2.0.0
    - numpy ==1.11.0
    - pandas >=0.19.2
    - peakutils >=1.0.3
    - pillow ==4.0.0
    - scipy ==0.18.1
    - statsmodels ==0.8.0
    - freesasa # [not win32]

test:
  # Python imports
  imports:
    - hydroid

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    # - HYDROID_test_exp --help
    # - HYDROID_test_pred --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ncbi/HYDROID
  license: Public Domain
  summary: 'HYDROID (HYDroxyl-Radical fOotprinting Interpretation for DNA) is a python package for the analysis of experimental data generated by hydroxyl-radical footprinting (HRF) of DNA-protein complexes'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
