package:
  name: seq_tools
  version: "0.1.0"

source:
  git_url: git@github.com:intbio/seq_tools
#  md5: d7936180ad4037962401c2302c1edd19
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - biopython 
    - pandas 
    - r-png
    - r-ggplot2
    - emboss
    - blast
    
  run:
    - python
    - setuptools
    - biopython 
    - pandas 
    - r-png
    - r-ggplot2
    - emboss
    - blast

test:
  # Python imports
  imports:
    - seq_tools

  # commands:
    # python example.py
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    # - HYDROID_test_exp --help
    # - HYDROID_test_pred --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/intbio/seq_tools
  license: Public Domain
  summary: 'A python package for visualization and manipulation of sequences and alignments'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
